export const LARGE_EXCHANGE_LOG_THRESHOLD_BYTES = 256 * 1024;
export const LARGE_EXCHANGE_LOG_THRESHOLD_ENTRIES = 80;
export const COMPACTION_SOURCE_FILENAME = "compaction-source.md";
export const COMPACTION_FALLBACK_SOURCE_FILENAME = "compaction-source-bounded.md";

export const BOUNDED_RECENT_EXCHANGE_MAX_BYTES = 64 * 1024;
export const BOUNDED_RECENT_PROGRESS_MAX_BYTES = 48 * 1024;
export const BOUNDED_ENTRY_FIELD_MAX_BYTES = 8 * 1024;
export const BOUNDED_PROGRESS_NOTE_MAX_BYTES = 8 * 1024;

export const BOUNDED_RECENT_EXCHANGE_TARGET_ENTRIES = 20;
export const BOUNDED_RECENT_PROGRESS_TARGET_NOTES = 40;
